### ISSUE TITLE
🐛 Bug - Popover Component Logs Warnings Due To Invalid Popper Usage

### ISSUE THREAD

**Issue by Chaoste** [contentful/forma-36#2363] opened 2023-01-02 15:07 UTC
# Forma 36 bug report

## Summary

When using the `Popover` and opening it, the console shows four warning logs about invalid properties being passed to [Popper](https://popper.js.org/) which is used for the popover functionality. As can be seen in [their docs](https://popper.js.org/docs/v2/modifiers/), modifiers need to specify properties like `name`, `enables`, `phase`, and `fn` while they are not defined always.

<img width="892" alt="Screenshot 2023-01-02 at 16 04 16" src="https://user-images.githubusercontent.com/9327071/210248780-a31fabd6-9ca8-4f16-ab43-63b73f5276f5.png">

## Environment

Mac, Chrome

## Steps to reproduce

Use PopOver and trigger it once to open the menu.

## Expected results

No spamming logs in the console

## Actual results

Warning logs

**Comment by Lelith** [comment] 2024-04-05 14:30
@denkristoffer @cf-remylenoir i can no longer reproduce this issue, has anyone of you seen this if this is still relevant?

**Comment by cf-remylenoir** [comment] 2024-04-08 07:40
Hey @Lelith, I can't reproduce it either.

**Comment by denkristoffer** [comment] 2024-04-08 08:53
Let's close it and revisit if we see it again.

**Closed by denkristoffer** 2024-04-08 08:53 UTC
Labels: bug
